
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'maven-build'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
