
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'acr-connection'
    repository: 'richaazuretest'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
